### ISSUE TITLE
カスタムスコープを指定する

### ISSUE THREAD

**Issue by kobayashi-m42** [nekochans/kimono-app-frontend#27]
# Doneの定義
- Cognitoに追加したカスタムスコープを指定できること

**Comment by keitakn** [comment]
@kobayashi-m42 課題作成ありがとう！
作業量は少ないだろうけど、 `@aws-amplify/ui-react` の設定調べないといけないから、ストーリーポイントは3とかかな🐱？

**Comment by kobayashi-m42** [comment]
@keitakn 設定を調べているんだけど、ドキュメントをみてもよくわからなかったから5くらいあった方がいいかも！

**Comment by keitakn** [comment]
@kobayashi-m42 
>設定を調べているんだけど、ドキュメントをみてもよくわからなかったから5くらいあった方がいいかも！

了解🐱！そしたら5でいこう！

**Comment by keitakn** [comment]
# めも
話し合った結果、かなり作り直しが発生するので、ストーリーポイントは多めに修正🐱

**Comment by keitakn** [comment]
# めも

Slackで話し合った結果、amplify.Authのライブラリだと現在はCustomScopeを設定出来ないので、CustomScopeは設定しない方向にする。

amplify.Authで将来的にscopeが追加出来るようになった時点でCustomScopeを使う可能性はあるが、少なくとも初期リリースの段階ではCustomScopeなしでも https://github.com/nekochans/kimono-app-api/issues/17 の実装は出来ると判断し、こちらはクローズにする。
